### ISSUE TITLE
I like how you chose to set the font-family once using a list of selectors!

### ISSUE THREAD

**Issue by jzhu01** [santiagobs/prj-rev-bwfs-dasmoto#3]
Seen here: 
https://github.com/santiagobs/prj-rev-bwfs-dasmoto/blob/b203d1a56d82e01ae93ffa945199d32f1f4a011a/Dasmoto/Resources/css/style.css#L1-L3
This was clean and efficient. I really like how you chose to set it up! :)

**Comment by santiagobs** [comment]
Thank you! I was wondering if using a html selector to change the entire font-family for all the tags would be good as well? 

html { 
   font-family: Helvetica; 
 }

**Comment by jzhu01** [comment]
Hi! I actually would recommend the body selector instead, since html also includes the head. But if that doesn't concern you, then html works as well!

**Comment by santiagobs** [comment]
Nice, thank you!
