### ISSUE TITLE
Suggestion - use IDs to select the h2

### ISSUE THREAD

**Issue by jzhu01** [santiagobs/prj-rev-bwfs-dasmoto#4]
Seen here: 
https://github.com/santiagobs/prj-rev-bwfs-dasmoto/blob/b203d1a56d82e01ae93ffa945199d32f1f4a011a/Dasmoto/Resources/css/style.css#L19-L29

Two things - you don't need to have the h2. predecessing any of your stylings (in general), it's enough to just select the class or ID. Secondly, I recommend using IDs here as these stylings are unique and do not repeat.

**Comment by santiagobs** [comment]
You're right, I will do exactly that, thank you!
